from typing import Optional
import sqlalchemy as sa
import sqlalchemy.orm as so
from web_app_main import db


# Function attempts to establish fields as class variables
# These will be the columns in the User db
# This is what populates the User db when the migration script is generated
# The migration script is generated by entering [flask db migrate -m "user table"] into the Python terminal
# (without brackets)
# To apply changes to the db from the migration script, [flask db upgrade] in the Python terminal
# (again without brackets)
# the script generation & upgrade must also be done when changes are made to the User db

class User(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(sa.String(64), index=True,
                                                unique=True)
    email: so.Mapped[str] = so.mapped_column(sa.String(128), index=True,
                                             unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))

    def __repr__(self):
        return '<User {}>'.format(self.username)
